version: '3.9'

services:
  app:
    build:
      context: backend
    ports:
      - "${LOCAL_APP_PORT}:8000"
    volumes:
      - ./backend:/app
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    environment:
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASS}
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
