version: '3.9'

services:
  app:
    build:
      context: backend
      args:
        - DEV=true
    ports:
      - "8003:8000"
    volumes:
      - ./backend:/app
    # command: >
    #   sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
